
help:
	@echo "Since you're here, you know how to get here."
	@echo "Type 'make help' in your terminal to get help."
	@echo "To run the code for subtask 1, enter 'make run', else to only compile 'make compile'."
	@echo "We love minimalism, only 3 commands to choose from."
run: compile
	./sub_task1
compile:
	g++ -ggdb sub_task1.cpp -o sub_task1 `pkg-config --cflags --libs opencv`
lalala:
	g++ -o lala lala.cpp
	./lala
